# Generated by Django 5.2.1 on 2026-05-14 20:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlists', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Вишлист',
                'verbose_name_plural': 'Вишлисты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WishlistAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist_accesses', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accesses', to='wishlists.wishlist', verbose_name='Вишлист')),
            ],
            options={
                'verbose_name': 'Доступ к вишлисту',
                'verbose_name_plural': 'Доступы к вишлистам',
                'ordering': ['-created_at'],
                'unique_together': {('wishlist', 'user')},
            },
        ),
        migrations.AddField(
            model_name='wishlist',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='assigned_wishlists', through='wishlists.WishlistAccess', to=settings.AUTH_USER_MODEL, verbose_name='Исполнители'),
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('product_url', models.URLField(blank=True, verbose_name='Ссылка на товар')),
                ('approximate_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Примерная цена')),
                ('priority', models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий')], default='medium', max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('not_done', 'Не выполнено'), ('in_progress', 'В процессе'), ('done', 'Выполнено')], default='not_done', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='wishlists.wishlist', verbose_name='Вишлист')),
            ],
            options={
                'verbose_name': 'Желание',
                'verbose_name_plural': 'Желания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ItemComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='wishlists.wishlistitem', verbose_name='Желание')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'ordering': ['created_at'],
            },
        ),
    ]
